language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -y update

install:

# OpenCV v3.2.0 install code (modified from https://gist.github.com/Randommood/478ccd806511d45febc1 orignal source: https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh)

# INSTALL THE DEPENDENCIES

  # OpenCV dependencies - Details available at: http://docs.opencv.org/trunk/doc/tutorials/introduction/linux_install/linux_install.html
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

# INSTALL THE LIBRARY (YOU CAN CHANGE '3.2.0' FOR THE LAST STABLE VERSION)

  - sudo apt-get install -y unzip wget
  - wget https://github.com/opencv/opencv/archive/3.2.0.zip
  - unzip 3.2.0.zip >/dev/null
  - rm 3.2.0.zip
  - mv opencv-3.2.0 OpenCV
  - wget https://github.com/opencv/opencv_contrib/archive/3.2.0.zip
  - unzip 3.2.0.zip >/dev/null
  - rm 3.2.0.zip
  - cd opencv_contrib-3.2.0
  - mkdir build
  - cd build
  - cmake -DOPENCV_EXTRA_MODULES_PATH=../modules ../../OpenCV
  - make -j5
  - sudo make install
  - sudo ldconfig

  - echo "OpenCV installed."

  # We need to return to the repo "root" folder, so we can then 'cd' into the C++ project folder.
  - cd ../../

script:
  - cmake .
  - make
